### ISSUE TITLE
9.10 Base Project is not compiling

### ISSUE THREAD

**Issue by MuriloGaming19** [zyloxmods/FNGameProj#8]
I installed all the required components for Visual Studio, and its gets an error to compile from source mannually, but when i compile from the solution, it gets a ton of errors related to "EnginePlugins"

**Comment by arm00n** [comment]
redownload the correct [engine](https://drive.google.com/u/1/uc?id=18_WeNsO-NSCEP-WNFmmi2ugSUSfEbsgQ&export=download) for 9.10 and you shouldn't be getting any errors. making an issue on github is kinda useless too as you'll get more help in the actual discord

**Comment by MuriloGaming19** [comment]
if you guys actually help me and not ignore my answers it could be awesome

**Comment by arm00n** [comment]
yeah imma continue ignoring them thank you very much

**Comment by MuriloGaming19** [comment]
why are you so mean for no reason?

**Comment by MuriloGaming19** [comment]
i just want some help

**Comment by arm00n** [comment]
and i gave it too you, i legit helped you with 90% of your issues which made me lose braincells in the process. you're legit the reason why i now give half assed responses to anyone asking for help now

**Comment by MuriloGaming19** [comment]
im sorry if i annoyed you, is bc i don't understand english too well

**Comment by arm00n** [comment]
dawg stop replying here 💀
